FROM node:20

WORKDIR /app

# نسخ ملفات الوصف
COPY package*.json ./

# تثبيت المكتبات
RUN npm install

# تثبيت الـ typescript عشان نحول الكود يدوي
RUN npm install -g typescript

# نسخ كود المشروع بالكامل
COPY . .

# تحويل الكود لـ JavaScript (أمر يدوي بدل npm run build)
RUN tsc

# البورت
EXPOSE 3000

# أمر التشغيل اللي جربتيه ونفع معاكي
CMD ["node", "dist/index.js"]