FROM node:20

WORKDIR /app

# 1. نسخ ملفات الوصف وتثبيت المكتبات
COPY package*.json ./
RUN npm install

# 2. تثبيت typescript بشكل عالمي عشان نستخدم أمر tsc
RUN npm install -g typescript

# 3. نسخ باقي الكود (بما فيهم الـ tsconfig.json)
COPY . .

# 4. البورت
EXPOSE 3000

# 5. التعديل السحري:
# بنقول للكونتينر: أول ما تفتح، "ابني" الكود الأول وبعدين "شغله"
# ده بيضمن إن الـ dist يتكريه بعد ما الـ Volumes تتركب
CMD ["sh", "-c", "tsc && node dist/index.js"]