events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # DNS بتاع الدوكر - مهم جداً عشان المتغيرات تشتغل
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        # 1. طلبات الـ API
        location /api/ {
            # بنعرف العنوان في متغير عشان الـ Nginx ما يقعش لو الباك إند اتأخر
            set $backend_endpoint http://deepguard_backend:3000;

            rewrite ^/api/(.*)$ /$1 break;

            proxy_pass         $backend_endpoint;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            
            # عشان الـ AI والملفات الكبيرة
            proxy_read_timeout 600s;
            client_max_body_size 100M;
        }

        # 2. الملفات المرفوعة
        location /uploads/ {
            alias /app/uploads/;
            expires 1d;
        }

        # 3. الـ Frontend (React/Vite)
        location / {
            set $frontend_endpoint http://front_node_container:5173;

            proxy_pass         $frontend_endpoint;
            proxy_http_version 1.1;

            # دعم الـ Hot Module Replacement (HMR)
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
            proxy_set_header   Host $host;

            # حل مشكلة الـ Refresh في React Router
            proxy_intercept_errors on;
            error_page 404 = /index.html;
        }
    }
}